name: fitness_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  card_loading: ^0.3.0
  cloud_firestore: ^4.6.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  equatable: ^2.0.5
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  icons_plus: ^4.0.0
  image_picker: ^0.8.7+5
  onboarding: ^3.1.0
  path_provider: ^2.0.14
  persistent_bottom_nav_bar: ^5.0.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
