name: fitness_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  card_loading: ^0.3.0
  cloud_firestore: ^4.6.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  dropdown_button2: ^2.3.6
  duration_picker: ^1.1.1
  equatable: ^2.0.5
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^15.1.0+1
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  icons_plus: ^4.0.0
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  onboarding: ^3.1.0
  path_provider: ^2.0.15
  persistent_bottom_nav_bar: ^5.0.2
  syncfusion_flutter_charts: ^22.1.37
  table_calendar: ^3.0.9
  timezone: ^0.9.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/fitness_app_logo.png"
  min_sdk_android: 21 

flutter:

  uses-material-design: true

  assets:
    - assets/images/
